### PR TITLE
Defines media route host from configured domain.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Related to https://github.com/open-orchestra/open-orchestra-media-bundle/pull/161

**Comment by alavieille** [comment]
:+1:

**Comment by ngilain** [comment]
@itkg-canne : It's a good idea, but I'm wondering: what about the protocol ?

**Comment by alavieille** [comment]
@itkg-ngilain if the protocol isn't specified, the symfony generate an url with the current protocol, with an url like this  `//YOUR_URL`

**Comment by ngilain** [comment]
Note: Maybe the solution is to set the scheme and the domain directly in the routing.yml

**Comment by ghost** [comment]
@itkg-ngilain 
Host and allowed schemes can also be configured like this in the routing.yml of the application :

```
open_orchestra_media:
    resource: "@OpenOrchestraMediaFileBundle/Controller"
    type: annotation
    prefix: /media
    host: '%my.media.domain.parameter'
    schemes: [http]
```

**Comment by alavieille** [comment]
@itkg-canne  
We can not merge this PR. in this case where open-orchestra-media-file-bundle isn't used in the front application this refactor doesn't work

**Pull request closed without merging**
